function remote_init(manufacturer, model)
    items={
        {name="Encoder 1", input="delta"},
        {name="Encoder 2", input="delta"},
        {name="Encoder 3", input="delta"},
        {name="Encoder 4", input="delta"},
        {name="Encoder 5", input="delta"},
        {name="Encoder 6", input="delta"},

        {name="L2 Encoder 1", input="delta"},
        {name="L2 Encoder 2", input="delta"},
        {name="L2 Encoder 3", input="delta"},
        {name="L2 Encoder 4", input="delta"},
        {name="L2 Encoder 5", input="delta"},
        {name="L2 Encoder 6", input="delta"},

        {name="L3 Encoder 1", input="delta"},
        {name="L3 Encoder 2", input="delta"},
        {name="L3 Encoder 3", input="delta"},
        {name="L3 Encoder 4", input="delta"},
        {name="L3 Encoder 5", input="delta"},
        {name="L3 Encoder 6", input="delta"},

        {name="Light 1", input="noinput", output="value", min=0, max=1},
        {name="Light 2", input="noinput", output="value", min=0, max=1},
        {name="Light 3", input="noinput", output="value", min=0, max=1},
        {name="Light 4", input="noinput", output="value", min=0, max=1},

        {name="L2 Light 1", input="noinput", output="value", min=0, max=1},
        {name="L2 Light 2", input="noinput", output="value", min=0, max=1},
        {name="L2 Light 3", input="noinput", output="value", min=0, max=1},
        {name="L2 Light 4", input="noinput", output="value", min=0, max=1},

        {name="L3 Light 1", input="noinput", output="value", min=0, max=1},
        {name="L3 Light 2", input="noinput", output="value", min=0, max=1},
        {name="L3 Light 3", input="noinput", output="value", min=0, max=1},
        {name="L3 Light 4", input="noinput", output="value", min=0, max=1},

        {name="Select 1", input="button"},
        {name="Select 2", input="button"},
        {name="Select 3", input="button"},
        {name="Select 4", input="button"},
        {name="Select 5", input="button"},
        {name="Select 6", input="button"},

        {name="L2 Select 1", input="button"},
        {name="L2 Select 2", input="button"},
        {name="L2 Select 3", input="button"},
        {name="L2 Select 4", input="button"},
        {name="L2 Select 5", input="button"},
        {name="L2 Select 6", input="button"},

        {name="L3 Select 1", input="button"},
        {name="L3 Select 2", input="button"},
        {name="L3 Select 3", input="button"},
        {name="L3 Select 4", input="button"},
        {name="L3 Select 5", input="button"},
        {name="L3 Select 6", input="button"},

        {name="Knob 1", input="value",output="value", min=0, max=127},
        {name="Knob 2", input="value",output="value", min=0, max=127},
        {name="Knob 3", input="value",output="value", min=0, max=127},
        {name="Knob 4", input="value",output="value", min=0, max=127},
        {name="Knob 5", input="value",output="value", min=0, max=127},
        {name="Knob 6", input="value",output="value", min=0, max=127},
        {name="Knob 7", input="value",output="value", min=0, max=127},
        {name="Knob 8", input="value",output="value", min=0, max=127},
        {name="Knob 9", input="value",output="value", min=0, max=127},
        {name="Knob 10", input="value",output="value", min=0, max=127},
        {name="Knob 11", input="value",output="value", min=0, max=127},
        {name="Knob 12", input="value",output="value", min=0, max=127},

        {name="Button 1", input="button",output="value"},
        {name="Button 2", input="button",output="value"},
        {name="Button 3", input="button",output="value"},
        {name="Button 4", input="button",output="value"},
        {name="Button 5", input="button",output="value"},
        {name="Button 6", input="button",output="value"},
        {name="Button 7", input="button",output="value"},
        {name="Button 8", input="button",output="value"},
        {name="Button 9", input="button",output="value"},
        {name="Button 10", input="button",output="value"},
        {name="Button 11", input="button",output="value"},
        {name="Button 12", input="button",output="value"},

        {name="L2 Knob 1", input="value",output="value", min=0, max=127},
        {name="L2 Knob 2", input="value",output="value", min=0, max=127},
        {name="L2 Knob 3", input="value",output="value", min=0, max=127},
        {name="L2 Knob 4", input="value",output="value", min=0, max=127},
        {name="L2 Knob 5", input="value",output="value", min=0, max=127},
        {name="L2 Knob 6", input="value",output="value", min=0, max=127},
        {name="L2 Knob 7", input="value",output="value", min=0, max=127},
        {name="L2 Knob 8", input="value",output="value", min=0, max=127},
        {name="L2 Knob 9", input="value",output="value", min=0, max=127},
        {name="L2 Knob 10", input="value",output="value", min=0, max=127},
        {name="L2 Knob 11", input="value",output="value", min=0, max=127},
        {name="L2 Knob 12", input="value",output="value", min=0, max=127},

        {name="L2 Button 1", input="button",output="value"},
        {name="L2 Button 2", input="button",output="value"},
        {name="L2 Button 3", input="button",output="value"},
        {name="L2 Button 4", input="button",output="value"},
        {name="L2 Button 5", input="button",output="value"},
        {name="L2 Button 6", input="button",output="value"},
        {name="L2 Button 7", input="button",output="value"},
        {name="L2 Button 8", input="button",output="value"},
        {name="L2 Button 9", input="button",output="value"},
        {name="L2 Button 10", input="button",output="value"},
        {name="L2 Button 11", input="button",output="value"},
        {name="L2 Button 12", input="button",output="value"},

        {name="L3 Knob 1", input="value",output="value", min=0, max=127},
        {name="L3 Knob 2", input="value",output="value", min=0, max=127},
        {name="L3 Knob 3", input="value",output="value", min=0, max=127},
        {name="L3 Knob 4", input="value",output="value", min=0, max=127},
        {name="L3 Knob 5", input="value",output="value", min=0, max=127},
        {name="L3 Knob 6", input="value",output="value", min=0, max=127},
        {name="L3 Knob 7", input="value",output="value", min=0, max=127},
        {name="L3 Knob 8", input="value",output="value", min=0, max=127},
        {name="L3 Knob 9", input="value",output="value", min=0, max=127},
        {name="L3 Knob 10", input="value",output="value", min=0, max=127},
        {name="L3 Knob 11", input="value",output="value", min=0, max=127},
        {name="L3 Knob 12", input="value",output="value", min=0, max=127},

        {name="L3 Button 1", input="button",output="value"},
        {name="L3 Button 2", input="button",output="value"},
        {name="L3 Button 3", input="button",output="value"},
        {name="L3 Button 4", input="button",output="value"},
        {name="L3 Button 5", input="button",output="value"},
        {name="L3 Button 6", input="button",output="value"},
        {name="L3 Button 7", input="button",output="value"},
        {name="L3 Button 8", input="button",output="value"},
        {name="L3 Button 9", input="button",output="value"},
        {name="L3 Button 10", input="button",output="value"},
        {name="L3 Button 11", input="button",output="value"},
        {name="L3 Button 12", input="button",output="value"},

        {name="Fader 1", input="value",output="value", min=0, max=127},
        {name="Fader 2", input="value",output="value", min=0, max=127},
        {name="Fader 3", input="value",output="value", min=0, max=127},
        {name="Fader 4", input="value",output="value", min=0, max=127},

        {name="L2 Fader 1", input="value",output="value", min=0, max=127},
        {name="L2 Fader 2", input="value",output="value", min=0, max=127},
        {name="L2 Fader 3", input="value",output="value", min=0, max=127},
        {name="L2 Fader 4", input="value",output="value", min=0, max=127},

        {name="L3 Fader 1", input="value",output="value", min=0, max=127},
        {name="L3 Fader 2", input="value",output="value", min=0, max=127},
        {name="L3 Fader 3", input="value",output="value", min=0, max=127},
        {name="L3 Fader 4", input="value",output="value", min=0, max=127},

        {name="Button A", input="button",output="value"},
        {name="Button B", input="button",output="value"},
        {name="Button C", input="button",output="value"},
        {name="Button D", input="button",output="value"},
        {name="Button E", input="button",output="value"},
        {name="Button F", input="button",output="value"},
        {name="Button G", input="button",output="value"},
        {name="Button H", input="button",output="value"},
        {name="Button I", input="button",output="value"},
        {name="Button J", input="button",output="value"},
        {name="Button K", input="button",output="value"},
        {name="Button L", input="button",output="value"},
        {name="Button M", input="button",output="value"},
        {name="Button N", input="button",output="value"},
        {name="Button O", input="button",output="value"},
        {name="Button P", input="button",output="value"},

        {name="L2 Button A", input="button",output="value"},
        {name="L2 Button B", input="button",output="value"},
        {name="L2 Button C", input="button",output="value"},
        {name="L2 Button D", input="button",output="value"},
        {name="L2 Button E", input="button",output="value"},
        {name="L2 Button F", input="button",output="value"},
        {name="L2 Button G", input="button",output="value"},
        {name="L2 Button H", input="button",output="value"},
        {name="L2 Button I", input="button",output="value"},
        {name="L2 Button J", input="button",output="value"},
        {name="L2 Button K", input="button",output="value"},
        {name="L2 Button L", input="button",output="value"},
        {name="L2 Button M", input="button",output="value"},
        {name="L2 Button N", input="button",output="value"},
        {name="L2 Button O", input="button",output="value"},
        {name="L2 Button P", input="button",output="value"},
        {name="L3 Button A", input="button",output="value"},
        {name="L3 Button B", input="button",output="value"},
        {name="L3 Button C", input="button",output="value"},
        {name="L3 Button D", input="button",output="value"},
        {name="L3 Button E", input="button",output="value"},
        {name="L3 Button F", input="button",output="value"},
        {name="L3 Button G", input="button",output="value"},
        {name="L3 Button H", input="button",output="value"},
        {name="L3 Button I", input="button",output="value"},
        {name="L3 Button J", input="button",output="value"},
        {name="L3 Button K", input="button",output="value"},
        {name="L3 Button L", input="button",output="value"},
        {name="L3 Button M", input="button",output="value"},
        {name="L3 Button N", input="button",output="value"},
        {name="L3 Button O", input="button",output="value"},
        {name="L3 Button P", input="button",output="value"},

        {name="Button Exit", input="button",output="value"},
        {name="L2 Button Exit", input="button",output="value"},
        {name="L3 Button Exit", input="button",output="value"},
    }
    remote.define_items(items)

    local inputs={
        {pattern="b? 00 xx", name="Encoder 1", value="convert(x)"},
        {pattern="b? 01 xx", name="Encoder 2", value="convert(x)"},
        {pattern="b? 02 xx", name="Encoder 3", value="convert(x)"},
        {pattern="b? 03 xx", name="Encoder 4", value="convert(x)"},
        {pattern="b? 14 xx", name="Encoder 5", value="convert(x)"},
        {pattern="b? 15 xx", name="Encoder 6", value="convert(x)"},

        {pattern="b? 16 xx", name="L2 Encoder 1", value="convert(x)"},
        {pattern="b? 17 xx", name="L2 Encoder 2", value="convert(x)"},
        {pattern="b? 18 xx", name="L2 Encoder 3", value="convert(x)"},
        {pattern="b? 19 xx", name="L2 Encoder 4", value="convert(x)"},
        {pattern="b? 2a xx", name="L2 Encoder 5", value="convert(x)"},
        {pattern="b? 2b xx", name="L2 Encoder 6", value="convert(x)"},

        {pattern="b? 2c xx", name="L3 Encoder 1", value="convert(x)"},
        {pattern="b? 2d xx", name="L3 Encoder 2", value="convert(x)"},
        {pattern="b? 2e xx", name="L3 Encoder 3", value="convert(x)"},
        {pattern="b? 2f xx", name="L3 Encoder 4", value="convert(x)"},
        {pattern="b? 44 xx", name="L3 Encoder 5", value="convert(x)"},
        {pattern="b? 45 xx", name="L3 Encoder 6", value="convert(x)"},

        {pattern="9? 34 xx", name="Select 1", value="1"},
        {pattern="9? 35 xx", name="Select 2", value="1"},
        {pattern="9? 36 xx", name="Select 3", value="1"},
        {pattern="9? 37 xx", name="Select 4", value="1"},
        {pattern="9? 0d xx", name="Select 5", value="1"},
        {pattern="9? 0e xx", name="Select 6", value="1"},

        {pattern="9? 58 xx", name="L2 Select 1", value="1"},
        {pattern="9? 59 xx", name="L2 Select 2", value="1"},
        {pattern="9? 5a xx", name="L2 Select 3", value="1"},
        {pattern="9? 5b xx", name="L2 Select 4", value="1"},
        {pattern="9? 11 xx", name="L2 Select 5", value="1"},
        {pattern="9? 12 xx", name="L2 Select 6", value="1"},

        {pattern="9? 7c xx", name="L3 Select 1", value="1"},
        {pattern="9? 7d xx", name="L3 Select 2", value="1"},
        {pattern="9? 7e xx", name="L3 Select 3", value="1"},
        {pattern="9? 7f xx", name="L3 Select 4", value="1"},
        {pattern="9? 15 xx", name="L3 Select 5", value="1"},
        {pattern="9? 16 xx", name="L3 Select 6", value="1"},

        {pattern="b? 04 xx", name="Knob 1"},
        {pattern="b? 05 xx", name="Knob 2"},
        {pattern="b? 06 xx", name="Knob 3"},
        {pattern="b? 07 xx", name="Knob 4"},
        {pattern="b? 08 xx", name="Knob 5"},
        {pattern="b? 09 xx", name="Knob 6"},
        {pattern="b? 0a xx", name="Knob 7"},
        {pattern="b? 0b xx", name="Knob 8"},
        {pattern="b? 0c xx", name="Knob 9"},
        {pattern="b? 0d xx", name="Knob 10"},
        {pattern="b? 0e xx", name="Knob 11"},
        {pattern="b? 0f xx", name="Knob 12"},

        {pattern="b? 1a xx", name="L2 Knob 1"},
        {pattern="b? 1b xx", name="L2 Knob 2"},
        {pattern="b? 1c xx", name="L2 Knob 3"},
        {pattern="b? 1d xx", name="L2 Knob 4"},
        {pattern="b? 1e xx", name="L2 Knob 5"},
        {pattern="b? 1f xx", name="L2 Knob 6"},
        {pattern="b? 20 xx", name="L2 Knob 7"},
        {pattern="b? 21 xx", name="L2 Knob 8"},
        {pattern="b? 22 xx", name="L2 Knob 9"},
        {pattern="b? 23 xx", name="L2 Knob 10"},
        {pattern="b? 24 xx", name="L2 Knob 11"},
        {pattern="b? 25 xx", name="L2 Knob 12"},

        {pattern="b? 30 xx", name="L3 Knob 1"},
        {pattern="b? 31 xx", name="L3 Knob 2"},
        {pattern="b? 32 xx", name="L3 Knob 3"},
        {pattern="b? 33 xx", name="L3 Knob 4"},
        {pattern="b? 34 xx", name="L3 Knob 5"},
        {pattern="b? 35 xx", name="L3 Knob 6"},
        {pattern="b? 36 xx", name="L3 Knob 7"},
        {pattern="b? 37 xx", name="L3 Knob 8"},
        {pattern="b? 38 xx", name="L3 Knob 9"},
        {pattern="b? 39 xx", name="L3 Knob 10"},
        {pattern="b? 3a xx", name="L3 Knob 11"},
        {pattern="b? 3b xx", name="L3 Knob 12"},

        {pattern="9? 30 xx", name="Button 1", value="1"},
        {pattern="9? 31 xx", name="Button 2", value="1"},
        {pattern="9? 32 xx", name="Button 3", value="1"},
        {pattern="9? 33 xx", name="Button 4", value="1"},
        {pattern="9? 2c xx", name="Button 5", value="1"},
        {pattern="9? 2d xx", name="Button 6", value="1"},
        {pattern="9? 2e xx", name="Button 7", value="1"},
        {pattern="9? 2f xx", name="Button 8", value="1"},
        {pattern="9? 28 xx", name="Button 9", value="1"},
        {pattern="9? 29 xx", name="Button 10", value="1"},
        {pattern="9? 2a xx", name="Button 11", value="1"},
        {pattern="9? 2b xx", name="Button 12", value="1"},

        {pattern="9? 54 xx", name="L2 Button 1", value="1"},
        {pattern="9? 55 xx", name="L2 Button 2", value="1"},
        {pattern="9? 56 xx", name="L2 Button 3", value="1"},
        {pattern="9? 57 xx", name="L2 Button 4", value="1"},
        {pattern="9? 50 xx", name="L2 Button 5", value="1"},
        {pattern="9? 51 xx", name="L2 Button 6", value="1"},
        {pattern="9? 52 xx", name="L2 Button 7", value="1"},
        {pattern="9? 53 xx", name="L2 Button 8", value="1"},
        {pattern="9? 4c xx", name="L2 Button 9", value="1"},
        {pattern="9? 4d xx", name="L2 Button 10", value="1"},
        {pattern="9? 4e xx", name="L2 Button 11", value="1"},
        {pattern="9? 4f xx", name="L2 Button 12", value="1"},

        {pattern="9? 78 xx", name="L3 Button 1", value="1"},
        {pattern="9? 79 xx", name="L3 Button 2", value="1"},
        {pattern="9? 7a xx", name="L3 Button 3", value="1"},
        {pattern="9? 7b xx", name="L3 Button 4", value="1"},
        {pattern="9? 74 xx", name="L3 Button 5", value="1"},
        {pattern="9? 75 xx", name="L3 Button 6", value="1"},
        {pattern="9? 76 xx", name="L3 Button 7", value="1"},
        {pattern="9? 77 xx", name="L3 Button 8", value="1"},
        {pattern="9? 70 xx", name="L3 Button 9", value="1"},
        {pattern="9? 71 xx", name="L3 Button 10", value="1"},
        {pattern="9? 72 xx", name="L3 Button 11", value="1"},
        {pattern="9? 73 xx", name="L3 Button 12", value="1"},

        {pattern="b? 10 xx", name="Fader 1"},
        {pattern="b? 11 xx", name="Fader 2"},
        {pattern="b? 12 xx", name="Fader 3"},
        {pattern="b? 13 xx", name="Fader 4"},

        {pattern="b? 26 xx", name="L2 Fader 1"},
        {pattern="b? 27 xx", name="L2 Fader 2"},
        {pattern="b? 28 xx", name="L2 Fader 3"},
        {pattern="b? 29 xx", name="L2 Fader 4"},

        {pattern="b? 3c xx", name="L3 Fader 1"},
        {pattern="b? 3d xx", name="L3 Fader 2"},
        {pattern="b? 3e xx", name="L3 Fader 3"},
        {pattern="b? 3f xx", name="L3 Fader 4"},

        {pattern="9? 24 xx", name="Button A", value="1"},
        {pattern="9? 25 xx", name="Button B", value="1"},
        {pattern="9? 26 xx", name="Button C", value="1"},
        {pattern="9? 27 xx", name="Button D", value="1"},
        {pattern="9? 20 xx", name="Button E", value="1"},
        {pattern="9? 21 xx", name="Button F", value="1"},
        {pattern="9? 22 xx", name="Button G", value="1"},
        {pattern="9? 23 xx", name="Button H", value="1"},
        {pattern="9? 1c xx", name="Button I", value="1"},
        {pattern="9? 1d xx", name="Button J", value="1"},
        {pattern="9? 1e xx", name="Button K", value="1"},
        {pattern="9? 1f xx", name="Button L", value="1"},
        {pattern="9? 18 xx", name="Button M", value="1"},
        {pattern="9? 19 xx", name="Button N", value="1"},
        {pattern="9? 1a xx", name="Button O", value="1"},
        {pattern="9? 1b xx", name="Button P", value="1"},

        {pattern="9? 48 xx", name="L2 Button A", value="1"},
        {pattern="9? 49 xx", name="L2 Button B", value="1"},
        {pattern="9? 4a xx", name="L2 Button C", value="1"},
        {pattern="9? 4b xx", name="L2 Button D", value="1"},
        {pattern="9? 44 xx", name="L2 Button E", value="1"},
        {pattern="9? 45 xx", name="L2 Button F", value="1"},
        {pattern="9? 46 xx", name="L2 Button G", value="1"},
        {pattern="9? 47 xx", name="L2 Button H", value="1"},
        {pattern="9? 40 xx", name="L2 Button I", value="1"},
        {pattern="9? 41 xx", name="L2 Button J", value="1"},
        {pattern="9? 42 xx", name="L2 Button K", value="1"},
        {pattern="9? 43 xx", name="L2 Button L", value="1"},
        {pattern="9? 3c xx", name="L2 Button M", value="1"},
        {pattern="9? 3d xx", name="L2 Button N", value="1"},
        {pattern="9? 3e xx", name="L2 Button O", value="1"},
        {pattern="9? 3f xx", name="L2 Button P", value="1"},

        {pattern="9? 6c xx", name="L3 Button A", value="1"},
        {pattern="9? 6d xx", name="L3 Button B", value="1"},
        {pattern="9? 6e xx", name="L3 Button C", value="1"},
        {pattern="9? 6f xx", name="L3 Button D", value="1"},
        {pattern="9? 68 xx", name="L3 Button E", value="1"},
        {pattern="9? 69 xx", name="L3 Button F", value="1"},
        {pattern="9? 6a xx", name="L3 Button G", value="1"},
        {pattern="9? 6b xx", name="L3 Button H", value="1"},
        {pattern="9? 64 xx", name="L3 Button I", value="1"},
        {pattern="9? 65 xx", name="L3 Button J", value="1"},
        {pattern="9? 66 xx", name="L3 Button K", value="1"},
        {pattern="9? 67 xx", name="L3 Button L", value="1"},
        {pattern="9? 60 xx", name="L3 Button M", value="1"},
        {pattern="9? 61 xx", name="L3 Button N", value="1"},
        {pattern="9? 62 xx", name="L3 Button O", value="1"},
        {pattern="9? 63 xx", name="L3 Button P", value="1"},

        {pattern="9? 0f xx", name="Button Exit", value="1"},

        {pattern="9? 13 xx", name="L2 Button Exit", value="1"},

        {pattern="9? 17 xx", name="L3 Button Exit", value="1"},
    }
    remote.define_auto_inputs(inputs)

    local outputs={

        {pattern="9e 34 xx", name="Light 1"},
        {pattern="9e 35 xx", name="Light 2"},
        {pattern="9e 36 xx", name="Light 3"},
        {pattern="9e 37 xx", name="Light 4"},

        {pattern="9e 58 xx", name="L2 Light 1"},
        {pattern="9e 59 xx", name="L2 Light 2"},
        {pattern="9e 5a xx", name="L2 Light 3"},
        {pattern="9e 5b xx", name="L2 Light 4"},

        {pattern="9e 7c xx", name="L3 Light 1"},
        {pattern="9e 7d xx", name="L3 Light 2"},
        {pattern="9e 7e xx", name="L3 Light 3"},
        {pattern="9e 7f xx", name="L3 Light 4"},

        {pattern="9e 30 xx", name="Button 1"},
        {pattern="9e 31 xx", name="Button 2"},
        {pattern="9e 32 xx", name="Button 3"},
        {pattern="9e 33 xx", name="Button 4"},
        {pattern="9e 2c xx", name="Button 5"},
        {pattern="9e 2d xx", name="Button 6"},
        {pattern="9e 2e xx", name="Button 7"},
        {pattern="9e 2f xx", name="Button 8"},
        {pattern="9e 28 xx", name="Button 9"},
        {pattern="9e 29 xx", name="Button 10"},
        {pattern="9e 2a xx", name="Button 11"},
        {pattern="9e 2b xx", name="Button 12"},

        {pattern="9e 54 xx", name="L2 Button 1"},
        {pattern="9e 55 xx", name="L2 Button 2"},
        {pattern="9e 56 xx", name="L2 Button 3"},
        {pattern="9e 57 xx", name="L2 Button 4"},
        {pattern="9e 50 xx", name="L2 Button 5"},
        {pattern="9e 51 xx", name="L2 Button 6"},
        {pattern="9e 52 xx", name="L2 Button 7"},
        {pattern="9e 53 xx", name="L2 Button 8"},
        {pattern="9e 4c xx", name="L2 Button 9"},
        {pattern="9e 4d xx", name="L2 Button 10"},
        {pattern="9e 4e xx", name="L2 Button 11"},
        {pattern="9e 4f xx", name="L2 Button 12"},

        {pattern="9e 78 xx", name="L3 Button 1"},
        {pattern="9e 79 xx", name="L3 Button 2"},
        {pattern="9e 7a xx", name="L3 Button 3"},
        {pattern="9e 7b xx", name="L3 Button 4"},
        {pattern="9e 74 xx", name="L3 Button 5"},
        {pattern="9e 75 xx", name="L3 Button 6"},
        {pattern="9e 76 xx", name="L3 Button 7"},
        {pattern="9e 77 xx", name="L3 Button 8"},
        {pattern="9e 70 xx", name="L3 Button 9"},
        {pattern="9e 71 xx", name="L3 Button 10"},
        {pattern="9e 72 xx", name="L3 Button 11"},
        {pattern="9e 73 xx", name="L3 Button 12"},

        {pattern="9e 24 xx", name="Button A"},
        {pattern="9e 25 xx", name="Button B"},
        {pattern="9e 26 xx", name="Button C"},
        {pattern="9e 27 xx", name="Button D"},
        {pattern="9e 20 xx", name="Button E"},
        {pattern="9e 21 xx", name="Button F"},
        {pattern="9e 22 xx", name="Button G"},
        {pattern="9e 23 xx", name="Button H"},
        {pattern="9e 1c xx", name="Button I"},
        {pattern="9e 1d xx", name="Button J"},
        {pattern="9e 1e xx", name="Button K"},
        {pattern="9e 1f xx", name="Button L"},
        {pattern="9e 18 xx", name="Button M"},
        {pattern="9e 19 xx", name="Button N"},
        {pattern="9e 1a xx", name="Button O"},
        {pattern="9e 1b xx", name="Button P"},

        {pattern="9e 48 xx", name="L2 Button A"},
        {pattern="9e 49 xx", name="L2 Button B"},
        {pattern="9e 4a xx", name="L2 Button C"},
        {pattern="9e 4b xx", name="L2 Button D"},
        {pattern="9e 44 xx", name="L2 Button E"},
        {pattern="9e 45 xx", name="L2 Button F"},
        {pattern="9e 46 xx", name="L2 Button G"},
        {pattern="9e 47 xx", name="L2 Button H"},
        {pattern="9e 40 xx", name="L2 Button I"},
        {pattern="9e 41 xx", name="L2 Button J"},
        {pattern="9e 42 xx", name="L2 Button K"},
        {pattern="9e 43 xx", name="L2 Button L"},
        {pattern="9e 3c xx", name="L2 Button M"},
        {pattern="9e 3d xx", name="L2 Button N"},
        {pattern="9e 3e xx", name="L2 Button O"},
        {pattern="9e 3f xx", name="L2 Button P"},

        {pattern="9e 6c xx", name="L3 Button A"},
        {pattern="9e 6d xx", name="L3 Button B"},
        {pattern="9e 6e xx", name="L3 Button C"},
        {pattern="9e 6f xx", name="L3 Button D"},
        {pattern="9e 68 xx", name="L3 Button E"},
        {pattern="9e 69 xx", name="L3 Button F"},
        {pattern="9e 6a xx", name="L3 Button G"},
        {pattern="9e 6b xx", name="L3 Button H"},
        {pattern="9e 64 xx", name="L3 Button I"},
        {pattern="9e 65 xx", name="L3 Button J"},
        {pattern="9e 66 xx", name="L3 Button K"},
        {pattern="9e 67 xx", name="L3 Button L"},
        {pattern="9e 60 xx", name="L3 Button M"},
        {pattern="9e 61 xx", name="L3 Button N"},
        {pattern="9e 62 xx", name="L3 Button O"},
        {pattern="9e 63 xx", name="L3 Button P"},

        {pattern="9e 0f xx", name="Button Exit"},
        {pattern="9e 13 xx", name="L2 Button Exit"},
        {pattern="9e 17 xx", name="L3 Button Exit"},

    }
    remote.define_auto_outputs(outputs)
end

function convert(x)
    if x > 1 then
        return -1
    else 
        return 1
    end
end
